// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uguKRXtZjm_3LHHixtUUfAvjNOpHzoY',
    appId: '1:412658300020:web:c672d094930c660b47cd21',
    messagingSenderId: '412658300020',
    projectId: 'todo-app-bd554',
    authDomain: 'todo-app-bd554.firebaseapp.com',
    storageBucket: 'todo-app-bd554.appspot.com',
    measurementId: 'G-RQPTTBHNV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxt2ixKqFyccgPPRLT0kUh3_5TUlu804',
    appId: '1:412658300020:android:d3e4f44413b8855847cd21',
    messagingSenderId: '412658300020',
    projectId: 'todo-app-bd554',
    storageBucket: 'todo-app-bd554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrnVjWzpoT6l4Xh8TkOC9CUj_SFImqoBk',
    appId: '1:412658300020:ios:087f5e634953673747cd21',
    messagingSenderId: '412658300020',
    projectId: 'todo-app-bd554',
    storageBucket: 'todo-app-bd554.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrnVjWzpoT6l4Xh8TkOC9CUj_SFImqoBk',
    appId: '1:412658300020:ios:087f5e634953673747cd21',
    messagingSenderId: '412658300020',
    projectId: 'todo-app-bd554',
    storageBucket: 'todo-app-bd554.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0uguKRXtZjm_3LHHixtUUfAvjNOpHzoY',
    appId: '1:412658300020:web:990843af8c324cd547cd21',
    messagingSenderId: '412658300020',
    projectId: 'todo-app-bd554',
    authDomain: 'todo-app-bd554.firebaseapp.com',
    storageBucket: 'todo-app-bd554.appspot.com',
    measurementId: 'G-TEMRH5822J',
  );
}
